### ISSUE TITLE
Car/Camera view is freezed - It doesn't move - Timeout for client answer

### ISSUE THREAD

**Issue by Amir-Ramezani** [ugo-nama-kun/gym_torcs#29]
Hi,

Thanks for your package.

I am trying to use it for RL and DNN but having problem with making it work. Basically my problem is that it kind of freezes. I tried to run the 'example_experiment.py' as well but the same thing happens, it runs TORCS environment and progresses until it starts the race but after that the car does't move or in another word camera view does now changes (it slowly, very slow, moves toward left but not forward). I am not sure where is the problem. I was trying to test it with python 2.x and 3.x and the following is the result:

--- with python2
amir-ai@Amir:~/gym_torcs$ python example_experiment.py 

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
TORCS Experiment Start.
Episode : 0
Waiting for server on 3101............
Count Down : 5
Waiting for server on 3101............
Count Down : 4
Waiting for server on 3101............
Count Down : 3
Waiting for server on 3101............
Count Down : 2
Waiting for server on 3101............
Count Down : 1
Waiting for server on 3101............
Count Down : 0
Waiting for server on 3101............
Count Down : -1
relaunch torcs

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for server on 3101............
Count Down : 4
Waiting for server on 3101............
Count Down : 3
Waiting for server on 3101............
Count Down : 2
Waiting for request on port 3101
Waiting for server on 3101............
Count Down : 1
Received from server: ***identified***
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
Traceback (most recent call last):
  File "example_experiment.py", line 24, in <module>
    ob = env.reset(relaunch=True)
  File "/home/amir-ai/gym_torcs/gym_torcs.py", line 192, in reset
    self.observation = self.make_observaton(obs)
  File "/home/amir-ai/gym_torcs/gym_torcs.py", line 275, in make_observaton
    image_rgb = self.obs_vision_to_image_rgb(raw_obs[names[8]])
  File "/home/amir-ai/gym_torcs/gym_torcs.py", line 232, in obs_vision_to_image_rgb
    r = image_vec[0:len(image_vec):3]
TypeError: object of type 'float' has no len()
amir-ai@Amir:~/gym_torcs$ Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
AL lib: ReleaseALC: 1 device not closed
^C

--- with python3

amir-ai@Amir:~/gym_torcs$ python3 example_experiment.py 
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
TORCS Experiment Start.
Episode : 0
Received from server: b'***identified***\x00'
Traceback (most recent call last):
  File "example_experiment.py", line 24, in <module>
    ob = env.reset(relaunch=True)
  File "/home/amir-ai/gym_torcs/gym_torcs.py", line 185, in reset
    self.client = snakeoil3.Client(p=3101, vision=self.vision)  # Open new UDP in vtorcs
  File "/home/amir-ai/gym_torcs/snakeoil3_gym.py", line 143, in __init__
    self.setup_connection()
  File "/home/amir-ai/gym_torcs/snakeoil3_gym.py", line 191, in setup_connection
    if identify in sockdata:
TypeError: 'str' does not support the buffer interface
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
amir-ai@Amir-SASLAB:~/gym_torcs$ Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer

---

Thanks,

**Comment by smasoudn** [comment]
Before running the `ddpy.py` try this:

> sudo torcs
    then go to   Race -> Quick Race -> Configure Race -> Accept  
Then make sure that `src_server1` has been selected and put focus on it

Then click on Accept and exit the game.... now run  `python ddpy.py` or your own work. 

Does it work?

**Comment by Amir-Ramezani** [comment]
Thanks for the answer.
But I am just wondering if I mentioned about 'ddpy.py'?

After all, it was a problem with 'gym_torcs.py' code (kind of settings in the code).

**Comment by quhezheng** [comment]
@AmirCognitive How did you fix that? I got into the same issue

**Comment by monicaMRL** [comment]
What setting did you change in gym_torcs?

**Comment by krasheninnikov** [comment]
Did someone figure it out? I have the same issue

**Comment by gchhor** [comment]
Hey! 
Any update on this issue? 
I keep on having the error: 

```
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
```
and then:

```
Timeout for client answer
Timeout for client answer
```

and the game restarts and so on and so forth..

**Comment by BCWang93** [comment]
@smasoudn  HI,I also have this problem,when I run ddpg.py.The terminal output 'Timeout for client answer'.Do you know how to solve it?Thanks!

**Comment by BCWang93** [comment]
@gchhor HI.Did you have solved this error?I also have this error?Can you help me?Thanks!

**Comment by BCWang93** [comment]
@Amir-Ramezani  HI.Do you solved this problem?I also has this issu recently.Can you help me?Thanks!

**Comment by KailoPictza** [comment]
Greetings! 
I have struggled with this issue for long now, and the solution was installing the patch indicated in the [documentation](https://arxiv.org/pdf/1304.1672.pdf) 

"Download the package `scr-linux-patch.tgz` containing the patch for the TORCS sources
from the CIG project page at [http://sourceforge.net/projects/cig/](http://sourceforge.net/projects/cig/)"

I hope this helps anyone in the future.
