### ISSUE TITLE
Error when running Torcs in vision mode

### ISSUE THREAD

**Issue by sahiliitm** [ugo-nama-kun/gym_torcs#9]
Hi,

When i run the default code and follow the instructions, I get the following error:

```
sahil@CoolToad:/gym_torcs$ python example_experiment.py 
pkill: killing pid 20651 failed: Operation not permitted
pkill: killing pid 20668 failed: Operation not permitted

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
TORCS Experiment Start.
Episode : 0
Client connected on 3101..............
cannot bind socketTraceback (most recent call last):
  File "example_experiment.py", line 24, in <module>
    ob = env.reset(relaunch=True)
  File "/gym_torcs/gym_torcs.py", line 190, in reset
    self.observation = self.make_observaton(obs)
  File "/gym_torcs/gym_torcs.py", line 267, in make_observaton
    image_rgb = self.obs_vision_to_image_rgb(raw_obs[names[8]])
KeyError: 'img'
```

Any idea why this happens?

**Comment by ugo-nama-kun** [comment]
Hi, 

Is it still possible to run without vision inputs?

**Comment by sahiliitm** [comment]
if I do that, I get a different error:

```

sahil@CoolToad:/gym_torcs$ python example_experiment.py 
pkill: killing pid 21686 failed: Operation not permitted
pkill: killing pid 21703 failed: Operation not permitted

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
TORCS Experiment Start.
Episode : 0
Client connected on 3101..............
cannot bind socketTraceback (most recent call last):
  File "example_experiment.py", line 32, in <module>
    ob, reward, done, _ = env.step(action)
  File "/gym_torcs/gym_torcs.py", line 89, in step
    client.R.d['accel'] += 1/(client.S.d['speedX']+.1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

**Comment by CarbonGU** [comment]
Hi
When I run `example_experiment.py`  with vision mode, I got a similar error:

`/usr/bin/python2.7 /home/carbongu/lib-install/OpenAI/gym_torcs/example_experiment.py
TORCS Experiment Start.
Episode : 0
Client connected on 3101..............
Traceback (most recent call last):
  File "/home/carbongu/lib-install/OpenAI/gym_torcs/example_experiment.py", line 24, in <module>
    ob = env.reset(relaunch=True)
  File "/home/carbongu/lib-install/OpenAI/gym_torcs/gym_torcs.py", line 192, in reset
    self.observation = self.make_observaton(obs)
  File "/home/carbongu/lib-install/OpenAI/gym_torcs/gym_torcs.py", line 275, in make_observaton
    image_rgb = self.obs_vision_to_image_rgb(raw_obs[names[8]])
  File "/home/carbongu/lib-install/OpenAI/gym_torcs/gym_torcs.py", line 232, in obs_vision_to_image_rgb
    r = image_vec[0:len(image_vec):3]
TypeError: object of type 'float' has no len()

Process finished with exit code 1`

Do you have any idea about it? Thanks

**Comment by AbdullahMohamed55** [comment]
@sahiliitm  Did you solve it ?
